[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[redirects]]
  from = "https://www.hebaelshimy.netlify.com"
  to = "https://www.hebaelshimy.com"
  status = 301
  force = true
  headers = {X-From = "Netlify"}