[[redirects]]
  from = "https://hebaelshimy.netlify.com/*"
  to = "https://www.hebaelshimy.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://hebaelshimy.netlify.com/*"
  to = "http://www.hebaelshimy.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.hebaelshimy.com/*"
  to = "https://www.hebaelshimy.com/:splat"
  status = 301
  force = true